FROM registry.access.redhat.com/ubi8/openjdk-21:1.19

WORKDIR /deployments

# Quarkus uber-jar (wird von mvn package erzeugt)
COPY target/WareHouse-1.0-SNAPSHOT-runner.jar app.jar
EXPOSE 8080

CMD ["java", "-jar", "/deployments/app.jar"]