import org.example.core.domain.Order;
import org.example.core.logic.WarehouseService;
import org.example.core.ports.out.IPersistOrderPort;
import org.example.core.results.NoContentResult;
import org.example.persistence.OrderStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;


public class Test1 {

    private IPersistOrderPort  persistOrderPort;
    private WarehouseService warehouseService;

    @BeforeEach
    void setUp() {
        // Mock only the port we need for this test
        persistOrderPort = Mockito.mock(IPersistOrderPort.class);

        warehouseService = new WarehouseService(null, persistOrderPort,null,null,null,null,null,null,null);
    }

    @Test
  void shouldHaveCreatedStatusWhenNewOrderIsProcessed() {

        Order order = new Order("Hubland", 5);
        // Tell the mock to return a successful result when persistOrder is called
        Mockito.when(persistOrderPort.persistOrder(any(Order.class)))
                .thenReturn(new NoContentResult());

        warehouseService.createOrder(order);

        assertEquals(OrderStatus.CREATED, order.getStatus());
        Mockito.verify(persistOrderPort, Mockito.times(1)).persistOrder(order);
    }

    @Test
    void createOrder_ShouldReturnResultWithGeneratedId() {
        // 1. Arrange: Create the order and the expected result
        Order order = new Order("Hubland", 3);

        NoContentResult mockResult = new NoContentResult();
        mockResult.setId(101L); // Simulate ID 101 generated by DB

        // Tell the mock what to return when called
        Mockito.when(persistOrderPort.persistOrder(any(Order.class))).thenReturn(mockResult);

        // 2. Act: Call the service
        NoContentResult actualResult = warehouseService.createOrder(order);

        // 3. Assert: Verify the ID reached the service result
        assertNotNull(actualResult.getId(), "The ID should not be null");
        assertEquals(101L, actualResult.getId(), "The ID should match the mock value");
        assertFalse(actualResult.hasError(), "There should be no error");
    }

}
